### ISSUE TITLE
I can not use @ in password - Please help

### ISSUE THREAD

**Issue by sanjayverma09** [thda/tds#23] opened 2020-12-11 11:55 UTC
While I am using a special character @ in the password it is not working after the first @ character it considers the host name. 
like 

db, err = sql.Open("tds", "tds://username:pass#word@abcde#xyz@hostname.com:1234?charset=utf8")

it is considering "abcde#xyz@hostname.com" rather then hostname.com

Please help!

**Comment by thda** [comment] 2020-12-14 08:30
Hi,

you should escape the user/password.
Please check [here](https://github.com/thda/tds/blob/1a2d89f5d5741816a6f3cfe7fd827399bf52fcf2/gsql/gsql.go#L102), in the sample program, how to build a query string.

Can you please try and let me know if it works for you ?

Cheers

**Comment by sanjayverma09** [comment] 2020-12-14 13:31
Not working. same error
my password having multiple special characters 
Please help!

**Comment by thda** [comment] 2020-12-14 15:45
Hi,

could you please share the error message ?

Thanks

**Comment by sanjayverma09** [comment] 2020-12-17 05:54
Hi, 
Thank you for your kind guidance,  that solution will help to use multiple types of passwords. 

I have now another problem -  the problem is we need to define a schema in the connection string.

Could. you please guide me on how I can define schema in connection string 
Please help!

**Comment by yohan212** [comment] 2020-12-18 11:22
Hi,
Same problem here, I can't specify a dbname... 
db, err := sql.Open("tds", "tds://username:password@hostname:port/dbname")
But when I make a query like select db_id(); The id is not the id of the db that i specify into the connection string ...

What can I do ? @thda 

Thank's in advance for you help

**Comment by thda** [comment] 2020-12-18 12:37
Hi,

I cannot reproduce your issue.
Can you please let me know your version ?

Also, can you please give me the default database of your login which you can find by using sp_displaylogin ?

Thanks

**Comment by yohan212** [comment] 2020-12-18 13:01
Thanks for your reply, 
this is my version: SQL Anywhere 16.0.0.2283.
I just need to connect to each database in my instance and check they are online.
I can't execute this stored procedure, (not found)

**Comment by yohan212** [comment] 2020-12-18 13:13
Everytime I do "select db_name()" is the default db whatever I put into the connection string

**Comment by sanjayverma09** [comment] 2020-12-18 14:14
Hi, thanks for your reply, 

my connection string is like below 
`db, err := sql.Open("tds", "tds://user:pass@host.com:1234/dbname?charset=utf8")`

I am getting below error 
`ErrorTrace": {
        "MsgNumber": 4002,
        "State": 0,
        "Severity": 14,
        "SQLState": "28000",
        "HasEed": 0,
        "TranState": 0,
        "Message": "SQL Anywhere Error -103: Invalid user ID or password",
        "Server": "",
        "Procedure": "",
        "LineNumber": 0
    }`
Please let me know if I need to do anything more except of this

**Comment by yohan212** [comment] 2020-12-18 15:17
This is a more detailed explanation
@thda  
```
package main

import (
	"database/sql"
	_ "flag"
	"fmt"
	"os"

	_ "github.com/thda/tds"
)

func main() {
	db, err := sql.Open("tds", "tds://username:password@IP:2638/dbnameA?charset=utf8")
	if err != nil {
		fmt.Printf("Failed to open database: %v", err)
		os.Exit(1)
	}
	defer db.Close()
	err = db.Ping()
	if err != nil {
		fmt.Printf("Failed to ping database: %v", err)
		os.Exit(1)
	}
	fmt.Println("ok")
	var result string
	row, _ := db.Query("select db_name()")
	for row.Next() {
		row.Scan(&result)
	}
	fmt.Println(result)
	os.Exit(0)

}
```
Response : 
`ok
dbnameB`


Thanks in advance for your help

**Comment by yohan212** [comment] 2020-12-18 15:39
NEWS:
It's working, I can make a query like "select * from table_of_dbnameA" but the procedure db_name() always return the dbnameb because it's my default db I suppose...

**Comment by yohan212** [comment] 2020-12-18 15:57
There is a way to prevent the driver to connect to the default database if the specify database is not available ?

**Comment by thda** [comment] 2020-12-22 22:19
@yohan212 can you please open a separate issue, with the exact version of your server, and copy/paste the description of your problem ?

**Comment by thda** [comment] 2020-12-22 22:22
@sanjayverma09 can you please let me know your servers' version and the charset ?
To get the charset please run:

`SELECT PROPERTY( 'CharSet' ), PROPERTY( 'DefaultCollation' ), PROPERTY( 'DefaultNcharCollation' )`

**Comment by thda** [comment] 2021-01-03 17:28
@sanjayverma09 , can you please provide the needful ? I cannot move forward without this information. Thanks

**Comment by thda** [comment] 2021-01-13 11:24
Without new data, I'll close this issue. Please reopen if you have the information.

**Closed as completed by thda** 2021-01-13 11:24 UTC
